language: c
sudo: required
dist: trusty

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

apt:
  packages:
    - gcc-multilib


matrix:

before_install:
  - $CC --version

before_script:

script:
  - make

